server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://dpg-d3oa4cre5dus73aii840-a.oregon-postgres.render.com:5432/apimhdb
    username: fesv_user
    password: SqlQpJYhc04BceCxO8ozwv89qlxgpNCo
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    secret: ChangeMeVerySecretKeyForDevPurposesChangeThis
    expirationSeconds: 86400
